/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BookingRequest { 
    requestId?: number;
    requestedBy?: number;
    requestedTo?: number;
    requestTypeId?: number;
    requestMessage?: string;
    requestDescription?: string;
    firstName?: string;
    lastName?: string;
    emailAddress?: string;
    phoneNumberLandLine?: string;
    phoneNumberMobile?: string;
    occassionId?: number;
    occassionName?: string;
    paymentMode?: string;
    cardNumber?: string;
    cost?: number;
    currency?: string;
    privateRequest?: boolean;
    requestForSelf?: boolean;
    requestStatusId?: number;
    relatedVideoUrl?: string;
    createdOn?: Date;
    createdBy?: number;
    updatedOn?: Date;
    updatedBy?: number;
    paymentComplete?: boolean;
    paymentCompleteOn?: Date;
    cancellationReason?: string;
}
