/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CelebItemBase { 
    id?: number;
    guid?: string;
    name?: string;
    imageUrl?: string;
    price?: number;
    currency?: string;
    active?: boolean;
    availableForBooking?: boolean;
    viewCount?: number;
    rating?: number;
}
