/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryItem } from './categoryItem';
import { Tagitem } from './tagitem';


export interface CelebProfile { 
    celebProfileId?: number;
    userId?: number;
    handleName?: string;
    displayName?: string;
    profession?: string;
    tagLine?: string;
    message?: string;
    includeInSearch?: boolean;
    followers?: number;
    likes?: number;
    rating?: number;
    tempInActive?: boolean;
    tempInActiveSetOn?: Date;
    tempInActiveReason?: string;
    availableForBooking?: boolean;
    minResponseDays?: number;
    maxResponseDays?: number;
    bookingPrice?: number;
    bookingPriceCurrency?: string;
    featured?: boolean;
    profileImageUrl?: string;
    profileVideoUrl?: string;
    facebookProfileUrl?: string;
    twitterProfileUrl?: string;
    instagramProfileUrl?: string;
    youtubeProfileUrl?: string;
    lastLoginOn?: Date;
    active?: boolean;
    createdOn?: Date;
    updatedOn?: Date;
    celebGuid?: string;
    categories?: Array<CategoryItem>;
    tags?: Array<Tagitem>;
}
