/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CelebItemBase } from './celebItemBase';


export interface MediaListItem { 
    celebDetails?: CelebItemBase;
    mediaId?: number;
    mediaGuid?: string;
    mediaName?: string;
    defaultUrl?: string;
    mediaType?: string;
    viewCount?: number;
    likeCount?: number;
    commentCount?: number;
    userId?: number;
    userName?: string;
}
