/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MediaObjectItem { 
    mediaExtension?: string;
    mediaSize?: number;
    mediumUrl?: string;
    highQualityUrl?: string;
    thumbnailUrl?: string;
    backgroundUrl?: string;
    createdBy?: number;
    userId?: number;
    createdOn?: Date;
    mediaId?: number;
    mediaGuid?: string;
    mediaName?: string;
    defaultUrl?: string;
    mediaType?: string;
    viewCount?: number;
    likeCount?: number;
    commentCount?: number;
    userName?: string;
}
