/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MediaCommentItem { 
    mediaId?: number;
    commentId?: number;
    userId?: number;
    commentBy?: string;
    comment?: string;
    rating?: number;
    createdOn?: Date;
}
