/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewBookingRequest { 
    requestedBy?: number;
    requestedTo?: number;
    requestTypeId?: NewBookingRequest.RequestTypeIdEnum;
    requestMessage?: string;
    requestDescription?: string;
    firstName?: string;
    lastName?: string;
    emailAddress?: string;
    phoneNumberLandLine?: string;
    phoneNumberMobile?: string;
    occassionId?: number;
    occassionName?: string;
    paymentMode?: string;
    cardNumber?: string;
    cost?: number;
    currency?: string;
    privateRequest?: boolean;
    requestForSelf?: boolean;
    readonly requestStatusId?: number;
    createdBy?: number;
    paymentComplete?: boolean;
    paymentCompleteOn?: Date;
}
export namespace NewBookingRequest {
    export type RequestTypeIdEnum = 1;
    export const RequestTypeIdEnum = {
        NUMBER_1: 1 as RequestTypeIdEnum
    };
}
