/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SearchItem { 
    id?: number;
    guid?: string;
    name?: string;
    imageUrl?: string;
    categories?: Array<string>;
    tags?: Array<string>;
    price?: number;
    currency?: string;
    tagLine?: string;
    description?: string;
    active?: boolean;
    availableForBooking?: boolean;
    handleName?: string;
}
