/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SignUpRequest { 
    firstName?: string;
    lastName?: string;
    email?: string;
    gender?: SignUpRequest.GenderEnum;
    birthdate?: Date;
    password?: string;
    password2?: string;
    readonly passwordMatch?: boolean;
}
export namespace SignUpRequest {
    export type GenderEnum = 0 | 1;
    export const GenderEnum = {
        NUMBER_0: 0 as GenderEnum,
        NUMBER_1: 1 as GenderEnum
    };
}
