/**
 * Fan API
 * Fan API
 *
 * OpenAPI spec version: v1.0
 * Contact: Dilip.Singh@market-Cube.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    userId?: number;
    userName?: string;
    firstName?: string;
    lastName?: string;
    emailAddress?: string;
    loginType?: string;
    birthDate?: Date;
    countryCode?: string;
    isCeleb?: boolean;
    active?: boolean;
    accountLocked?: boolean;
    comment?: string;
    gender?: string;
    resetPassword?: boolean;
    profileImageUrl?: string;
    userGuid?: string;
}
